var OX_ea1b8dca = '';
OX_ea1b8dca += "<"+"div  style=\"clear:both; margin-top: 40px;;\">\n";
OX_ea1b8dca += "<"+"!-- Яндекс.Директ -->\n";
OX_ea1b8dca += "<"+"script type=\"text/javascript\"><"+"!--\n";
OX_ea1b8dca += "yandex_partner_id = 16476;\n";
OX_ea1b8dca += "yandex_site_bg_color = \'FFFFFF\';\n";
OX_ea1b8dca += "yandex_site_charset = \'utf-8\';\n";
OX_ea1b8dca += "yandex_ad_format = \'direct\';\n";
OX_ea1b8dca += "yandex_font_size = 0.9;\n";
OX_ea1b8dca += "yandex_direct_type = \'horizontal\';\n";
OX_ea1b8dca += "yandex_direct_border_type = \'ad\';\n";
OX_ea1b8dca += "yandex_direct_limit = 4;\n";
OX_ea1b8dca += "yandex_direct_header_bg_color = \'CC0000\';\n";
OX_ea1b8dca += "yandex_direct_bg_color = \'FFFFCC\';\n";
OX_ea1b8dca += "yandex_direct_border_color = \'FBE5C0\';\n";
OX_ea1b8dca += "yandex_direct_title_color = \'000000\';\n";
OX_ea1b8dca += "yandex_direct_url_color = \'000000\';\n";
OX_ea1b8dca += "yandex_direct_all_color = \'000000\';\n";
OX_ea1b8dca += "yandex_direct_text_color = \'000000\';\n";
OX_ea1b8dca += "yandex_direct_hover_color = \'FF0000\';\n";
OX_ea1b8dca += "document.write(\'<"+"sc\'+\'ript type=\"text/javascript\" src=\"http://an.yandex.ru/system/context.js\"><"+"/sc\'+\'ript>\');\n";
OX_ea1b8dca += "//--><"+"/script>\n";
OX_ea1b8dca += "<"+"/div>\n";
OX_ea1b8dca += "<"+"div  style=\"clear:both; margin-top: 40px;;\">\n";
OX_ea1b8dca += "<"+"!-- Яндекс.Маркет -->\n";
OX_ea1b8dca += "<"+"script type=\"text/javascript\">\n";
OX_ea1b8dca += "//<"+"![CDATA[\n";
OX_ea1b8dca += "yandex_partner_id = 16476;\n";
OX_ea1b8dca += "yandex_site_bg_color = \'FFFFFF\';\n";
OX_ea1b8dca += "yandex_site_charset = \'utf-8\';\n";
OX_ea1b8dca += "yandex_ad_format = \'market\';\n";
OX_ea1b8dca += "yandex_font_size = 0.9;\n";
OX_ea1b8dca += "yandex_market_type = \'horizontal\';\n";
OX_ea1b8dca += "yandex_market_border_type = \'ad\';\n";
OX_ea1b8dca += "yandex_market_limit = 4;\n";
OX_ea1b8dca += "yandex_market_header_bg_color = \'CC0000\';\n";
OX_ea1b8dca += "yandex_market_bg_color = \'FFFFCC\';\n";
OX_ea1b8dca += "yandex_market_border_color = \'FFE6CC\';\n";
OX_ea1b8dca += "yandex_market_title_color = \'000000\';\n";
OX_ea1b8dca += "yandex_market_category_color = \'666666\';\n";
OX_ea1b8dca += "yandex_market_all_color = \'000000\';\n";
OX_ea1b8dca += "yandex_market_text_color = \'000000\';\n";
OX_ea1b8dca += "yandex_market_hover_color = \'CCCCCC\';\n";
OX_ea1b8dca += "document.write(\'<"+"sc\'+\'ript type=\"text/javascript\" src=\"http://an.yandex.ru/system/context.js\"><"+"/sc\'+\'ript>\');\n";
OX_ea1b8dca += "//]]>\n";
OX_ea1b8dca += "<"+"/script>\n";
OX_ea1b8dca += "<"+"/div><"+"div id=\'beacon_252a50617c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://www.tadviser.ru/openx/www/delivery/lg.php?bannerid=35&amp;campaignid=4&amp;zoneid=18&amp;loc=1&amp;referer=http%3A%2F%2Fwww.tadviser.ru%2Findex.php%2F%25D0%25A1%25D1%2582%25D0%25B0%25D1%2582%25D1%258C%25D1%258F%3AInfrastructure_as_a_Service%2C_IaaS_%28%25D0%25BC%25D0%25B8%25D1%2580%25D0%25BE%25D0%25B2%25D0%25BE%25D0%25B9_%25D1%2580%25D1%258B%25D0%25BD%25D0%25BE%25D0%25BA%29&amp;cb=252a50617c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"script type=\'text/javascript\'>document.context=\'cDoyNjQjcDozNDN8\'; <"+"/script>\n";
document.write(OX_ea1b8dca);
